#!/bin/bash

GIT_REPO="https://github.com/7agustibm/dotfiles.git"
DOTFILES_DIR=$HOME.dotfiles

set -Xe

cd $HOME

git clone --recursive ${GIT_FLAGS} ${GIT_REPO} ${DOTFILES_DIR}

# Package managers & packages

. "$DOTFILES_DIR/install/brew.sh"
. "$DOTFILES_DIR/install/bash.sh"
. "$DOTFILES_DIR/install/ohmyz.sh"

if [ "$(uname)" == "Darwin" ]; then
    . "$DOTFILES_DIR/install/brew-cask.sh"
fi

# Bunch of symlinks

ln -sfv "$DOTFILES_DIR/zsh/.zshrc" ~
ln -sfv "$DOTFILES_DIR/git/.gitconfig" ~
ln -sfv "$DOTFILES_DIR/git/.gitignore" ~

echo "All Done!"
